#Use Render
spring.datasource.url=jdbc:postgresql://ep-calm-feather-a1928yje-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NBh3iExe6Ing

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

#Localhost
#spring.datasource.url=jdbc:postgresql://localhost:5432/research
#spring.datasource.username=postgres
#spring.datasource.password=1234


spring.datasource.hikari.connection-timeout=600000
spring.datasource.hikari.maximum-pool-size=50000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.idle-timeout=60000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=${PORT:8080}

